// API URL 注册表：只定义端点路径，http 请求统一走 services/
export const URLS = {
  auth: {
    token: '/auth/token',
    me: '/auth/me',
    password: '/auth/password',
  },
  users: {
    list: '/users',
    tenants: '/tenants',
    secrets: '/secrets',
    roles: '/roles',
    roleUsers: (roleId: string) => `/roles/${encodeURIComponent(roleId)}/users`,
  },
  health: '/health/ha',
  meta: '/meta',
  runs: {
    list: '/agents/runs',
    stream: '/agents/runs/stream',
    detail: (id: string) => `/agents/runs/${id}`,
    cost: (id: string) => `/agents/runs/${id}/cost`,
    pause: (id: string) => `/agents/runs/${id}/pause`,
    resume: (id: string) => `/agents/runs/${id}/resume`,
    cancel: (id: string) => `/agents/runs/${id}/cancel`,
    replay: (id: string) => `/agents/runs/${id}/replay`,
    compare: (id: string) => `/agents/runs/${id}/compare`,
    schedule: (id: string) => `/agents/runs/${id}/schedule`,
    scheduleCompare: (id: string) => `/agents/runs/${id}/schedule/compare`,
    payloads: (id: string) => `/agents/runs/${id}/trace/payloads`,
    feedback: (id: string) => `/agents/runs/${id}/feedback`,
  },
  sessions: {
    list: '/agents/sessions',
    messages: (id: string) => `/agents/sessions/${encodeURIComponent(id)}/messages`,
    patch: (id: string) => `/agents/sessions/${encodeURIComponent(id)}`,
    messageDelete: (sid: string, mid: string) =>
      `/agents/sessions/${encodeURIComponent(sid)}/messages/${encodeURIComponent(mid)}`,
  },
  model: {
    health: '/model/health',
    config: '/model/config',
  },
  release: {
    versions: (agentId: string) => `/agents/${agentId}/versions`,
    publish: (agentId: string, v: number) => `/agents/${agentId}/versions/${v}/publish`,
    gray: (agentId: string, v: number) => `/agents/${agentId}/versions/${v}/gray`,
    rollback: (agentId: string) => `/agents/${agentId}/rollback`,
    halt: (agentId: string, v: number) => `/agents/${agentId}/versions/${v}/halt`,
    contract: (agentId: string, v: number) => `/agents/${agentId}/versions/${v}/contract-check`,
    regression: (agentId: string, v: number) => `/agents/${agentId}/versions/${v}/regression`,
    security: (agentId: string, v: number) => `/agents/${agentId}/versions/${v}/security-eval`,
    metrics: (agentId: string) => `/agents/${agentId}/release-metrics`,
    canaryCheck: (agentId: string) => `/agents/${agentId}/canary/check`,
    canaryEvaluate: (agentId: string) => `/agents/${agentId}/canary/evaluate`,
    flow: (agentId: string) => `/agents/${agentId}/release-flow`,
    flowNode: (agentId: string, code: string) => `/agents/${agentId}/release-flow/${code}`,
    flowTerminate: (agentId: string) => `/agents/${agentId}/release-flow/terminate`,
    flowHistory: (agentId: string) => `/agents/${agentId}/flow-history`,
  },
  knowledge: {
    bases: '/knowledge/bases',
    base: (id: string) => `/knowledge/bases/${encodeURIComponent(id)}`,
    baseConfig: (id: string) => `/knowledge/bases/${encodeURIComponent(id)}/config`,
    documents: '/knowledge/documents',
    document: (id: string) => `/knowledge/documents/${encodeURIComponent(id)}`,
    preview: '/knowledge/preview',
    search: '/knowledge/search',
    uploadInit: '/knowledge/upload/init',
    uploadChunk: (uploadId: string, index: number) => `/knowledge/upload/${uploadId}/chunks/${index}`,
    uploadStatus: (uploadId: string) => `/knowledge/upload/${uploadId}/status`,
    uploadComplete: (uploadId: string) => `/knowledge/upload/${uploadId}/complete`,
    uploadDocument: '/knowledge/documents/upload',
  },
  cost: { overview: '/cost/overview', growth: '/cost/growth', usage: '/cost/usage', reconcile: '/cost/reconcile' },
  tools: { list: '/tools', execute: (ref: string) => `/tools/${ref}/execute` },
  mcp: { list: '/mcp/servers', delete: (name: string) => `/mcp/servers/${encodeURIComponent(name)}` },
  customTools: { list: '/custom-tools', delete: (ref: string) => `/custom-tools/${encodeURIComponent(ref)}` },
  events: {
    list: '/events',
    stats: '/events/stats',
    publish: '/events/publish',
    replay: (agg: string) => `/events/replay/${encodeURIComponent(agg)}`,
    aggregateState: (agg: string) => `/events/aggregate/${encodeURIComponent(agg)}/state`,
  },
  queue: {
    jobs: '/queue/jobs',
    stats: '/queue/stats',
    job: (id: string) => `/queue/jobs/${encodeURIComponent(id)}`,
    requeue: (jobId: string) => `/queue/jobs/${jobId}/requeue`,
    cancel: (jobId: string) => `/queue/jobs/${jobId}/cancel`,
    expire: '/queue/jobs/expire',
    sample: '/queue/sample',
  },
  approvals: { list: '/approvals', detail: (id: string) => `/approvals/${encodeURIComponent(id)}`, approve: (id: string) => `/approvals/${id}/approve`, reject: (id: string) => `/approvals/${id}/reject` },
  policies: { list: '/policies', meta: '/policies/meta', detail: (id: string) => `/policies/${encodeURIComponent(id)}` },
  audit: { list: '/audit' },
  data: { sweep: '/data/sweep', purgeTenant: (tenantId: string) => `/data/tenant/${tenantId}/purge` },
  eval: {
    cases: '/evaluations/cases',
    seed: '/evaluations/cases/seed',
    seedConfig: '/evaluations/seed-config',
    regressionRuns: (agentId: string) => `/agents/${agentId}/regression-runs`,
  },
  graph: {
    query: '/graph/query',
    entity: (name: string) => `/graph/entity/${encodeURIComponent(name)}`,
    facts: '/graph/facts',
    extract: '/graph/extract',
    merge: (name: string) => `/graph/entities/${encodeURIComponent(name)}/merge`,
  },
  memory: { write: '/memory', recall: '/memory/recall', delete: (id: string) => `/memory/${id}` },
  config: {
    get: '/config',
    versions: (key: string) => `/config/${encodeURIComponent(key)}/versions`,
    version: (key: string, v: number) => `/config/${encodeURIComponent(key)}/versions/${v}`,
  },
  flags: { set: '/flags', get: (key: string) => `/flags/${encodeURIComponent(key)}` },
}
