"""align current models

Revision ID: a89bccbd6b84
Revises: 0006_agent_run_version
Create Date: 2026-08-21 19:45:49.926370

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a89bccbd6b84"
down_revision: str | Sequence[str] | None = "0006_agent_run_version"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "configurations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("scope_id", sa.String(length=64), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value_json", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "scope", "scope_id", "key", "version", name="uq_config_ver"),
    )
    with op.batch_alter_table("configurations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_configurations_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "entities",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("aliases_json", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("entities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_entities_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "evaluation_cases",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("dataset_id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("expected_json", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("evaluation_cases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_evaluation_cases_dataset_id"), ["dataset_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_evaluation_cases_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "evaluation_datasets",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("evaluation_datasets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_evaluation_datasets_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "feature_flags",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("rules_json", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("feature_flags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_feature_flags_key"), ["key"], unique=False)
        batch_op.create_index(batch_op.f("ix_feature_flags_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "knowledge_facts",
        sa.Column("fact_id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("subject_entity", sa.String(length=255), nullable=False),
        sa.Column("predicate", sa.String(length=255), nullable=False),
        sa.Column("object", sa.String(length=255), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source_doc", sa.String(length=255), nullable=False),
        sa.Column("source_chunk", sa.String(length=64), nullable=False),
        sa.Column("source_version", sa.String(length=64), nullable=False),
        sa.Column("extracted_by", sa.String(length=255), nullable=False),
        sa.Column("sources_json", sa.Text(), nullable=False),
        sa.Column(
            "valid_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("fact_id"),
    )
    with op.batch_alter_table("knowledge_facts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_knowledge_facts_subject_entity"), ["subject_entity"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_knowledge_facts_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "llm_calls",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("step_id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("agent_id", sa.String(length=64), nullable=False),
        sa.Column("agent_version", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("cached_input_tokens", sa.Integer(), nullable=False),
        sa.Column("reasoning_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost", sa.Float(), nullable=False),
        sa.Column("actual_cost", sa.Float(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("scheduler_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("llm_calls", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_llm_calls_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_llm_calls_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "trace_payloads",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("span_name", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("trace_payloads", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_trace_payloads_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_trace_payloads_trace_id"), ["trace_id"], unique=False)

    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("replay_of", sa.String(length=64), nullable=True))

    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_column("correlation_id")

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_column("lease_until")

    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("correlation_id", sa.VARCHAR(length=64), nullable=False))

    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.drop_column("replay_of")

    with op.batch_alter_table("trace_payloads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trace_payloads_trace_id"))
        batch_op.drop_index(batch_op.f("ix_trace_payloads_run_id"))

    op.drop_table("trace_payloads")
    with op.batch_alter_table("llm_calls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llm_calls_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_llm_calls_run_id"))

    op.drop_table("llm_calls")
    with op.batch_alter_table("knowledge_facts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_knowledge_facts_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_knowledge_facts_subject_entity"))

    op.drop_table("knowledge_facts")
    with op.batch_alter_table("feature_flags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feature_flags_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_feature_flags_key"))

    op.drop_table("feature_flags")
    with op.batch_alter_table("evaluation_datasets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evaluation_datasets_tenant_id"))

    op.drop_table("evaluation_datasets")
    with op.batch_alter_table("evaluation_cases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evaluation_cases_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_evaluation_cases_dataset_id"))

    op.drop_table("evaluation_cases")
    with op.batch_alter_table("entities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_entities_tenant_id"))

    op.drop_table("entities")
    with op.batch_alter_table("configurations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_configurations_tenant_id"))

    op.drop_table("configurations")
    # ### end Alembic commands ###
