"""sync models (fill migration drift)

Revision ID: bc26410ab6cd
Revises: 0009_user_password_hash
Create Date: 2026-08-23 16:35:51.958183

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc26410ab6cd"
down_revision: str | Sequence[str] | None = "0009_user_password_hash"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("kb_id", sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f("ix_chunks_kb_id"), ["kb_id"], unique=False)

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.add_column(sa.Column("kb_id", sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f("ix_documents_kb_id"), ["kb_id"], unique=False)

    with op.batch_alter_table("memories", schema=None) as batch_op:
        batch_op.add_column(sa.Column("embedding", sa.Text(), nullable=False))

    with op.batch_alter_table("policies", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("role_id", sa.String(length=64), nullable=True))

    with op.batch_alter_table("secrets", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            existing_server_default=sa.text("now()"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("secrets", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=True,
            existing_server_default=sa.text("now()"),
        )

    with op.batch_alter_table("policies", schema=None) as batch_op:
        batch_op.drop_column("role_id")
        batch_op.drop_column("user_id")

    with op.batch_alter_table("memories", schema=None) as batch_op:
        batch_op.drop_column("embedding")

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_kb_id"))
        batch_op.drop_column("kb_id")

    with op.batch_alter_table("chunks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chunks_kb_id"))
        batch_op.drop_column("kb_id")

    # ### end Alembic commands ###
